// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsWsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WS_NOT_FOUND.String() && e.Code == 404
}

func ErrorWsNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_WS_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CONTENT_MISSING.String() && e.Code == 400
}

func ErrorContentMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsLoginFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_LOGIN_FAILED.String() && e.Code == 401
}

func ErrorLoginFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_LOGIN_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsCreateWholesaleDrug(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CREATE_WHOLESALE_DRUG.String() && e.Code == 201
}

func ErrorCreateWholesaleDrug(format string, args ...interface{}) *errors.Error {
	return errors.New(201, ErrorReason_CREATE_WHOLESALE_DRUG.String(), fmt.Sprintf(format, args...))
}
